name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
    - name: Build
      run: go build -v ./...
    - name: Build Docker images
      run: |
        docker build -t scraper -f services/scraper/Dockerfile .
        docker build -t consumer -f services/consumer/Dockerfile .
        docker build -t metrics -f services/metrics/Dockerfile .